### ISSUE TITLE
NuGet Package does not show up as an analyzer in VS Solution Explorer

### ISSUE THREAD

**Issue by BrightLight** [Litee/moq.analyzers#8]
The package that is available on nuget.org (and here on GitHub) does not show up in the Visual Studio Solution explorer under "Analyzers". I think the reason for this is that the package stores the dll in `\lib\netstandard1.3` instead of `\analyzers\dotnet\cs`
![NuGetPackageExplorer_Moq Analyzers_0 0 9](https://user-images.githubusercontent.com/1859278/176994537-b0acaa4a-b13e-4d76-a761-46ba2372d64d.png)

I tried to investigate this a bit, but both the `Diagnostic.nuspec` and `Moq.Analyzers.csproj` look fine. Both use "analyzers\dotnet\cs" as the path. I don't know which of these two is used to built the actual nuget, my guess is `Diagnostic.nuspec` as it's using 0.0.9 while the csproj is still on 0.0.6.

Could you please upload an updated nuget with the correct path?

**Comment by rjmurillo** [comment]
Hi @BrightLight. Thanks for the issue report. We are working toward a new release that will correct this issue.

**Comment by rjmurillo** [comment]
Hi @BrightLight this has been fixed in version [0.1.0](https://www.nuget.org/packages/Moq.Analyzers/0.1.0#readme-body-tab).
